# Generated by Django 3.0.5 on 2020-07-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=20)),
                ('track_id', models.CharField(max_length=20)),
                ('is_Delete', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
