# Generated by Django 3.0.5 on 2020-07-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_resiger'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_resiger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
            ],
        ),
    ]
