# Generated by Django 3.0.5 on 2020-08-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_myblog_total_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='img',
        ),
    ]
