# Generated by Django 3.0.5 on 2020-07-30 06:42

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_new_resiger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', mdeditor.fields.MDTextField()),
            ],
            options={
                'verbose_name': '博客发布',
                'verbose_name_plural': '博客发布',
            },
        ),
    ]
