# Generated by Django 3.0.5 on 2020-07-31 10:34

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_auto_20200730_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBlog1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('list', models.CharField(max_length=30)),
                ('content', mdeditor.fields.MDTextField()),
                ('img', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '博客发布',
                'verbose_name_plural': '博客发布',
            },
        ),
    ]
